### ISSUE TITLE
State naming

### ISSUE THREAD

**Issue by bloesch** [ethz-asl/generalized_information_filter#6]
The naming of the State is missleading. Proposition:
- Keep Element/ElementDefinition as it is. This is along the lines of std::tuple. The term "Block" is less appropriate as it hints at matrices/vectors.
- Change State/StateDefinition to either Tuple (keeping the std::tuple concept), or Set, or ElementSet...
- Adapt ElementPack as well: name it such that it is clear that it represents the compile time version of "StateDefinition".

Any alternatives?

**Comment by schneith** [comment]
What about using "PartitioningInformation" for the StateDefinintion and PartitionedVector for the State?
I have made a short draft of the interfaces here: https://gist.github.com/schneith/d359d9548456f888823823a60aec1671.

What do you mean by changing the State to a tuple? To fix the dimensions at compile-time for the state too?

**Comment by bloesch** [comment]
It is not really a vector (strictly speaking also not in a vector space). The current "State" is more like a collection or a set of "Elements" (using something like the cartesian product). And as the std tuple is relatively similar (except for the compile time aspect) we may use the same naming. In the end it is a hybrid runtime/compiletime tuple concept.

But I guess the partioning/vector concept could also work, I need some time to look at your draft.

**Comment by bloesch** [comment]
I think the partioning approach is interesting. A couple of questions to clarify things on my side:
- Where does the actual data get stored (SO3)? Also a partioned vector?
- Where do you implement the difference between SO3 and so3?

**Comment by schneith** [comment]
The partitioned vector could be just beneath the actual implementations that additionally implement all special functions. SO3 would be stored in a State vector:
```
class State : public PartitionedMatrix { 
  // State specific functionality if required.
};
```

Would it generally be possible only keep temporaries of so3 and never explicitly store it? If not it could be added to the State class. Some hacky draft:
```
class State  { 
  // State specific functionality if required.
  State(PartitionInfomation state_partitioning) {
    x_ambient = PartitionInfomation::CreateVectorAmbient(state_partitioning);
    delta_x_tangent = PartitionInfomation::CreateVectorTangent(state_partitioning);
  }

  // Add deltas to state.
  void retract();

  // Forwarders to 2x PartitionedMatrix fcts.
  ...

 private:
  PartitionedMatrix x_ambient;
  PartitionedMatrix delta_x_tangent;
};
```

**Comment by bloesch** [comment]
So you would use a partioned vector for both State and differences. There are a couple of tasks which explicetly require the difference on so3. For instance the Kalman update or while computing the finite differences.

Keeping the delta_x_tangent as member of State could be of advantage for boxplus/boxminus operations which do are not smooth when changing the reference point (e.g. if working with bearing vectors on S2). However, you may loose a bit of flexibility (there is not always a 1:1 relation).

**Comment by bloesch** [comment]
Just for the record: here is a design we discussed together with @schneith: https://gist.github.com/bloesch/2d42e5e71eaeae90a7f9dff40cf34e40 .

We will stick with "Data in Element" approach for the beginning and might consider refactoring in future.
